#!/usr/bin/env python3
"""Bucket partition of the i3-suite results, and the README blocks built from it.

Usage: i3_buckets.py [--write README]   (print, or rewrite, the generated regions)

Every assertion of every pinned snapshot lands in exactly one bucket:
P pass; S upstream skip; N-i3 i3-only premise; N-x11-all X11 premise neither
measured stack meets (sway 1.12's wlroots XWM, swayward's xwayland-satellite);
N-x11-sway X11 metadata swayward cannot get through xwayland-satellite;
N-harness measurement artefact; N-gap comparable non-pass.

Precedence per assertion: flaky file > unstable assertion > pass > skip >
reviewed swayward_*_finding label in an EWMH/XTEST abort file > file-level
abort override (unreached rows only) > verified abort cause from
i3/abort-causes/ (unreached, unverified rows) > other unverified unreached
rows (N-harness) > family map > unverified fail (N-gap).

Inputs: pins.toml, pending.toml, i3/results, i3/classifications,
i3/unstable.toml, i3/abort-causes. contrib/tests/readme-snapshots requires each
README block's generated region to equal render_region().
"""
import collections
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUCKETS = ["P", "S", "N-i3", "N-x11-all", "N-x11-sway", "N-harness", "N-gap"]
EXCLUDED = {"N-i3", "N-x11-all", "N-harness"}
RAW = ["pass", "skip", "fail", "unreached", "unstable", "flaky"]
REFERENCE = "sway"
NO_TAP = "The pinned run emitted no TAP plan; retain this as an environment or harness finding."
KILL = "xwm_kill_client_fallback"
MIRROR = "MIRROR"
BEGIN = "<!-- i3-suite: generated by contrib/i3_buckets.py from the committed results; do not edit by hand -->"
END = "<!-- end i3-suite -->"

# Family -> bucket.
FAMILY = {
    # i3-only premises, or i3 semantics sway rejects by design (source-cited in the family text)
    "i3_parser_internals": "N-i3", "i3_append_layout": "N-i3", "sway_no_append_layout": "N-i3",
    "i3_open_command": "N-i3", "sway_command_vocabulary": "N-i3", "sway_config_text": "N-i3",
    "i3_fake_outputs": "N-i3", "workspace_layout_stacked_keyword": "N-i3",
    "sway_ipc_root_border_width": "N-i3", "sway_ipc_internal_border_width": "N-i3",
    "sway_focus_workspace_command": "N-i3", "sway_hidden_scratchpad_floating": "N-i3",
    "sway_config_include_ipc": "N-i3", "sway_xwayland_maximized_state": "N-i3",
    "i3_output_selection_semantics": "N-i3", "i3_workspace_rename_semantics": "N-i3",
    # X11 premises neither measured stack meets headless
    "headless_xtest_boundary": "N-x11-all",
    # swayward-only X11 metadata boundary (xwayland-satellite -> xdg_toplevel)
    "xwayland_satellite_metadata_limit": "N-x11-sway", "xwayland_satellite_no_x11_class": "N-x11-sway",
    "xwayland_satellite_no_dynamic_x11_state": "N-x11-sway",
    KILL: "KILL",  # per assertion: N-x11-all if sway also non-pass, else N-x11-sway
    # harness / adapter; swayward_adapter_finding rows "remain explicit failures"
    "swayward_adapter_finding": "N-gap", "sway_validate_adapter_finding": "N-harness",
    "xwayland_client_geometry": "N-harness",
    # comparable non-passes
    "sway_tree_semantics_finding": "N-gap", "sway_ipc_semantics_finding": "N-gap",
    "sway_command_semantics_finding": "N-gap", "sway_xwayland_geometry_finding": "N-gap",
    "sway_xwayland_mapping_finding": "N-gap",
    "swayward_tree_finding": "N-gap", "swayward_ipc_finding": "N-gap", "swayward_command_finding": "N-gap",
    "swayward_geometry_finding": "N-gap", "swayward_mapping_finding": "N-gap",
    "sway_no_bar": "N-gap", "sway_product_version": "N-gap",  # declared swayward deviations
}
DECLARED = {"sway_no_bar", "sway_product_version"}

# File-level abort causes for UNREACHED rows, decided from the i3/t source.
# They override the per-row reason because the row never ran.
ABORT = {
    "302-tree.t": ("N-i3", "cmp_tree->append_layout"),
    "306-move-to-parent.t": ("N-i3", "cmp_tree->append_layout"),
    "307-focus-next-prev.t": ("N-i3", "cmp_tree->append_layout"),
    "308-focus_wrapping.t": ("N-i3", "cmp_tree->append_layout"),
    "309-crash-move-parent.t": ("N-i3", "cmp_tree->append_layout"),
    "550-split-redundant-containers.t": ("N-i3", "cmp_tree->append_layout"),
    "117-workspace.t": ("N-i3", "i3 output content node traversal"),
    "185-scratchpad.t": ("N-i3", "i3 __i3 output content node traversal"),
    "159-socketpaths.t": ("N-i3", "i3 socket-path conventions"),
    "262-config-validation.t": ("N-i3", "i3 -C validate + i3 log"),
    "289-ipc-shutdown-event.t": ("N-i3", "i3 in-place restart"),
    "266-net-moveresize-window.t": ("N-x11-all", "EWMH _NET_MOVERESIZE_WINDOW"),
    "284-ewmh-visible-name.t": ("N-x11-all", "EWMH _NET_WM_VISIBLE_NAME"),
    "310-client-message-sticky.t": ("N-x11-all", "EWMH _NET_WM_DESKTOP client message"),
    "135-floating-focus.t": ("N-x11-all", "kill disconnects i3test X client"),
    "286-root-window-mouse-binding.t": ("N-x11-all", "XTEST button press"),
    "166-assign.t": ("N-harness", "abort cause undetermined; swayward aborts at A17 before any kill"),
    "556-workspace-keeps-focus-after-move.t": ("N-harness", "65,536 sync_with_i3 loop vs settle-poll shim"),
    "202-scratchpad-criteria.t": ("N-x11-all", "kill disconnects i3test X client"),
}
# EWMH/XTEST abort files: a verified swayward_*_finding label wins over ABORT.
KEEP_REVIEWED = {"266-net-moveresize-window.t", "284-ewmh-visible-name.t",
                 "310-client-message-sticky.t", "286-root-window-mouse-binding.t"}
# Compositor-specific abort overrides (unreached rows only).
ABORT_ONE = {("sway", "113-urgent.t"): ("N-x11-all", "kill disconnects i3test X client"),
             ("sway", "264-dock-criteria.t"): ("N-x11-all", "kill disconnects i3test X client")}
EVIDENCE = {"kill": "kill disconnects i3test X client", "xtest": "XTEST blocks in xtest_sync_with_i3"}


def load(path):
    with open(ROOT / path, "rb") as f:
        return tomllib.load(f)


def display(compositor, name, commit):
    version = name.removeprefix(f"{compositor}-")
    return f"{compositor} `{version}`" if version == commit[:8] else f"{compositor} {version}"


class Snapshot:
    def __init__(self, compositor, name, unstable, pending):
        self.compositor, self.name = compositor, name
        self.files = load(f"i3/results/{name}.toml")["files"]
        self.rows = load(f"i3/classifications/{name}.toml")["classification"]
        self.labels = {(r["file"], r["assertion"]): r for r in self.rows}
        self.unstable = {(f, a) for c, f, a in unstable if c == compositor}
        self.stale = f"i3/results/{name}.toml" in pending
        self.outcome = {(f, a): o for f, e in self.files.items()
                        for o in ("pass", "skip", "fail", "unreached")
                        for a in e.get(f"{o}_assertions", [])}
        self.keys = [(f, a) for f in sorted(self.files) for a in range(1, self.files[f]["assertions"] + 1)]
        evidence = ROOT / f"i3/abort-causes/{name}.toml"
        self.evidence = {row["file"]: row["cause"]
                         for row in (load(evidence.relative_to(ROOT)).get("file", []) if evidence.exists() else [])}
        clash = set(self.evidence) & (set(ABORT) | {f for c, f in ABORT_ONE if c == compositor})
        if clash:
            raise SystemExit(f"{evidence}: files also have a source-decided abort override: {sorted(clash)}")
        self.bucket, self.cause = {}, {}
        # Snapshots whose results the partition reads; a pending one marks every figure.
        self.inputs = {self}

    def raw(self, key):
        if self.files[key[0]].get("flaky"):
            return "flaky"
        if key in self.unstable:
            return "unstable"
        return self.outcome[key]

    def classify(self, key, reference):
        f, a = key
        if self.files[f].get("flaky"):
            return "N-harness", "flaky file"
        if key in self.unstable:
            return "N-harness", "unstable assertion"
        o = self.outcome.get(key)
        if o is None:
            raise SystemExit(f"{self.name}: {f}:{a} has no outcome")
        if o == "pass":
            return "P", "pass"
        if o == "skip":
            return "S", "upstream skip"
        row = self.labels.get(key)
        if row is None:
            raise SystemExit(f"{self.name}: non-pass {f}:{a} has no classification")
        reason, verified = row["reason"], row["reason_verified"]
        if o == "unreached":
            if f in KEEP_REVIEWED and verified and reason.startswith("swayward_") \
                    and reason.endswith("_finding") and FAMILY.get(reason) == "N-gap":
                return "N-gap", "reviewed label kept in an EWMH/XTEST abort file: " + reason
            override = ABORT_ONE.get((self.compositor, f)) or ABORT.get(f)
            if override:
                return override[0], "abort point decided from the test source: " + override[1]
            if not verified:
                cause = self.evidence.get(f)
                if cause in EVIDENCE:
                    return "N-x11-all", "abort cause verified by a focused rerun: " + EVIDENCE[cause]
                return "N-harness", "unreached, abort cause undetermined"
        if reason in FAMILY:
            bucket = FAMILY[reason]
            if bucket == "KILL":
                if reference.bucket.get(key) == "P":
                    return "N-x11-sway", "kill label, sway passes"
                if o == "fail":
                    # The row ran, so the kill boundary cannot explain it: mirror sway.
                    return MIRROR, "kill label on a row that ran; mirrors sway"
                return "N-x11-all", "family: " + reason
            return bucket, ("declared deviation: " if reason in DECLARED else "family: ") + reason
        if reason in (NO_TAP, "unclassified"):
            return "N-gap", "fail, not yet reviewed"
        raise SystemExit(f"{self.name}: unmapped reason {reason!r} for {f}:{a}")

    def partition(self, reference):
        # Kill-labelled rows are bucketed by the reference's outcome, so every
        # figure of this snapshot can depend on the reference result.
        if any(r["reason"] == KILL for r in self.rows):
            self.inputs.add(reference)
        for key in self.keys:
            bucket, cause = self.classify(key, reference)
            if bucket == MIRROR:
                bucket = reference.bucket[key]
                bucket = "N-gap" if bucket in ("P", "S") else bucket
            self.bucket[key], self.cause[key] = bucket, cause
        for counts in (collections.Counter(self.bucket.values()),
                       collections.Counter(map(self.raw, self.keys))):
            if sum(counts.values()) != len(self.keys):
                raise SystemExit(f"{self.name}: partition does not sum to {len(self.keys)}")

    def view(self):
        return {k for k in self.keys if self.bucket[k] not in EXCLUDED}


def snapshots(pending=None):
    pins = load("pins.toml")
    if pending is None:
        pending = {row["path"] for row in load("pending.toml").get("pending", [])}
    unstable = {(u["compositor"], u["file"], a) for u in load("i3/unstable.toml").get("unstable", [])
                for a in u["assertions"]}
    snaps = {c: Snapshot(c, n, unstable, pending) for c, n in pins["snapshot"].items()}
    keys = {tuple(s.keys) for s in snaps.values()}
    if len(keys) != 1:
        raise SystemExit("i3 results do not cover the same assertions")
    reference = snaps[REFERENCE]
    reference.partition(reference)
    for snap in snaps.values():
        if snap is not reference:
            snap.partition(reference)
    return pins, snaps


def n(value):
    return f"{value:,}"


def dagger(*snaps):
    """† when any result these snapshots' partitions read is pending."""
    return "†" if any(s.stale for snap in snaps for s in snap.inputs) else ""


def render_region(compositor, pins, snaps):
    snap = snaps[compositor]
    mark = dagger(snap)
    review = "†" if snap.stale else ""
    counts = collections.Counter(snap.bucket.values())
    notes = collections.Counter(snap.cause.values())
    verified_aborts = sum(v for c, v in notes.items() if c.startswith("abort cause verified"))
    unreviewed = notes["fail, not yet reviewed"]
    cells = []
    for bucket in BUCKETS:
        cell = n(counts[bucket]) + mark
        if bucket == "N-x11-all" and verified_aborts:
            cell += f" ({n(verified_aborts)}{mark} abort causes verified by focused reruns)"
        if bucket == "N-gap" and unreviewed:
            cell += f" ({n(unreviewed)}{mark} not yet reviewed)"
        cells.append(cell)
    verified = sum(r.get("reason_verified") is True for r in snap.rows)
    unclassified = sum(r.get("reason") == "unclassified" for r in snap.rows)
    noun = "row" if len(snap.rows) == 1 else "rows"
    view = snap.view()
    vb = collections.Counter(snap.bucket[k] for k in view)
    vr = collections.Counter(snap.raw(k) for k in view)
    title = display(compositor, snap.name, pins[compositor])
    lines = [
        BEGIN,
        "| " + " | ".join(BUCKETS) + " |",
        "|" + " ---: |" * len(BUCKETS),
        "| " + " | ".join(cells) + " |",
        "",
        f"i3-suite review: {n(len(snap.rows))}{review} non-pass {noun}; {n(verified)}{review} verified, "
        f"{n(len(snap.rows) - verified)}{review} unverified, {n(unclassified)}{review} of them unclassified.",
        "",
        f"Comparable view of {title} ({n(len(view))}{mark} rows):",
        "",
        "| P | S | N-x11-sway | N-gap | " + " | ".join(RAW) + " |",
        "|" + " ---: |" * (4 + len(RAW)),
        "| " + " | ".join(n(x) + mark for x in [vb["P"], vb["S"], vb["N-x11-sway"], vb["N-gap"]]
                          + [vr[o] for o in RAW]) + " |",
        "",
    ]
    full = len(view) == len(snap.keys)
    others = [] if full else [c for c, s in snaps.items() if c != compositor and s.view() != set(s.keys)]
    if full:
        lines.append(f"Asymmetries: {compositor}'s view excludes no rows: every assertion is P or S.")
    for other in others:
        theirs = snaps[other]
        pair = dagger(snap, theirs)
        only = [k for k in view if k not in theirs.view()]
        shared = len(view) - len(only)
        passed = sum(snap.bucket[k] == "P" for k in only)
        lines.append(
            f"Asymmetries: {compositor}'s view and {other}'s view share {n(shared)}{pair} rows. "
            f"{n(len(only))}{pair} rows are in {compositor}'s view only, excluded by {other}'s labels, "
            f"and {compositor} passes {n(passed)}{pair} of them. By {other}'s bucket and cause:")
        lines.append("")
        by = collections.Counter((theirs.bucket[k], theirs.cause[k]) for k in only)
        for (bucket, cause), count in sorted(by.items(), key=lambda x: (-x[1], x[0])):
            cause = re.sub(r"(?<=: )([a-z0-9_]+)$", r"`\1`", cause)
            lines.append(f"- {n(count)}{pair} {bucket}: {cause}")
        lines.append("")
        lines.append(f"Measured on {compositor}'s view, {other} has "
                     f"{n(sum(theirs.bucket[k] == 'P' for k in view))}{pair} P.")
    lines.append(END)
    return "\n".join(lines)


def regions(text):
    return re.findall(rf"^{re.escape(BEGIN)}\n.*?^{re.escape(END)}$", text, re.S | re.M)


def write(path):
    pins, snaps = snapshots()
    text = Path(path).read_text()
    found = regions(text)
    if len(found) != len(snaps):
        raise SystemExit(f"{path}: needs {len(snaps)} generated i3-suite regions, found {len(found)}")
    # Regions appear in pins.toml [snapshot] order, one per block.
    for old, compositor in zip(found, snaps):
        text = text.replace(old, render_region(compositor, pins, snaps), 1)
    Path(path).write_text(text)


if __name__ == "__main__":
    if sys.argv[1:2] == ["--write"] and len(sys.argv) == 3:
        write(sys.argv[2])
    elif len(sys.argv) == 1:
        pins, snaps = snapshots()
        for compositor in snaps:
            print(render_region(compositor, pins, snaps), end="\n\n")
    else:
        raise SystemExit(__doc__)
